# Source: acme/templates/cert-manager-prod-certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "tls-aurum-com-br-p"
  labels:
    jenkins.io/letsencrypt-service: production
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  secretName: "tls-aurum-com-br-p"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.aurum.com.br"
  dnsNames:
    - "*.aurum.com.br"
    - "aurum.com.br"
