# Source: jxboot-helmfile-resources/templates/docker-cfg-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-docker-cfg
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: gcpSecretsManager
  projectId: aurum-services
  data:
    - name: config.json
      key: jenkins-x-v1-jenkins-docker-cfg
      property: config.json
      version: latest
  template:
    type: Opaque
