apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    devEnvApprovers:
    - TiagoMMSccp
    - gumaestri
    - cunhazord
    environmentGitOwner: aurumsoftware
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: gke
    registry: gcr.io
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: "jx.aurum.com.br"
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: "devops@aurum.com.br"
      enabled: true
      production: false
  repository: nexus
  secretStorage: gsm
  vault: {}
  webhook: lighthouse
