# Source: acme/templates/cert-manager-staging-clusterissuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "devops@aurum.com.br"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - selector:
          dnsNames:
            - "*.aurum.com.br"
            - "aurum.com.br"
        # ACME DNS-01 provider configurations
        dns01:
          cloudDNS:
            # The project in which to update the DNS zone
            project: "aurum-services"
