# Source: jenkins/templates/secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins
  namespace: jx
  labels:
    "app.kubernetes.io/name": 'jenkins'
    "helm.sh/chart": "jenkins-3.0.11"
    "app.kubernetes.io/managed-by": "Helm"
    "app.kubernetes.io/instance": "jenkins"
    "app.kubernetes.io/component": "jenkins-controller"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    secret.jenkins-x.io/schema-object: '{"name":"jenkins","properties":[{"name":"jenkins-admin-user","question":"the pipeline username","help":"the user to login to Jenkins","defaultValue":"admin"},{"name":"jenkins-admin-password","question":"the pipeline token or password","help":"the password to login to Jenkins","generator":"password"}],"mandatory":true}'
spec:
  backendType: gcpSecretsManager
  projectId: aurum-services
  data:
    - name: jenkins-admin-password
      key: jenkins-x-v1-jenkins
      property: jenkins-admin-password
      version: latest
    - name: jenkins-admin-user
      key: jenkins-x-v1-jenkins
      property: jenkins-admin-user
      version: latest
  template:
    metadata:
      labels:
        "app.kubernetes.io/name": 'jenkins'
        "helm.sh/chart": "jenkins-3.0.11"
        "app.kubernetes.io/managed-by": "Helm"
        "app.kubernetes.io/instance": "jenkins"
        "app.kubernetes.io/component": "jenkins-controller"
      annotations:
        secret.jenkins-x.io/schema-object: '{"name":"jenkins","properties":[{"name":"jenkins-admin-user","question":"the pipeline username","help":"the user to login to Jenkins","defaultValue":"admin"},{"name":"jenkins-admin-password","question":"the pipeline token or password","help":"the password to login to Jenkins","generator":"password"}],"mandatory":true}'
    type: Opaque
